### ISSUE TITLE
The logo in the  demo WebCourse is poorly cropped

### ISSUE THREAD

**Issue by SirL3X0N** [eclectic-bytech/webcourses-ngx-v4#134] opened 2022-12-12 08:57 UTC
When I loaded into webcourses catalogue and clicked the webcourse-demo webcourse I noticed that the three ring part of the big logo was cut off on the left side. i also noticed the lower half of the 'S' was also cut off. It doesn't appear to be this way in the top left of the page so i figured I'd write this issue

**Comment by bytech-ca** [comment] 2022-12-12 21:23
Hmm, not seeing this issue. Please post link and screen shot of what it looks like on your end. Might be a screen size limitation...

**Comment by SirL3X0N** [comment] 2022-12-13 08:27
![poorcrop](https://user-images.githubusercontent.com/116177078/207264517-2aca8737-6f65-4405-a9d2-1a8864f89ad2.png)

**Comment by bytech-ca** [comment] 2022-12-13 11:57
Hmmm... is your zoom at 1:1? I _sooooometimes_ get a slight cut to the logo when zooming all over the place. On 1:1, it always looks good in FF. When loading the image directly (right click image, and select open image in new window) it always looks perfect, regardless of zoom.

![My-web-courses](https://user-images.githubusercontent.com/33671154/207311083-2ab3b488-19a1-4707-8f95-1fb35117da9c.png)

If you can add extra steps to reproduce (the conditions under which this happens), please add here. Otherwise, let's close the issue due its tiny weight, limited occurrence and a super limited audience (for the most part, only platform admins will ever see this course.)

**Closed** 2022-12-14 08:17 UTC
Labels: bug
